include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/l10n/gen/*
    - test/generated_migrations/**
  errors:
    non_abstract_class_inherits_abstract_member: ignore

linter:
  rules:
    public_member_api_docs: false
